//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_floor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int id { get; set; }
        public string matName { get; set; }
        public Nullable<decimal> defectPercent { get; set; }
    }
}
