//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_floor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int id { get; set; }
        public string partName { get; set; }
        public Nullable<int> typeId { get; set; }
        public string director { get; set; }
        public string phoneNum { get; set; }
        public string partAddress { get; set; }
        public Nullable<int> rating { get; set; }
        public string INN { get; set; }
        public string email { get; set; }
    
        public virtual PartTypes PartTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
