//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_floor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int id { get; set; }
        public Nullable<int> prodId { get; set; }
        public Nullable<int> partId { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> saleDate { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
